# Workflow per desplegar automàticament a Railway quan els tests passen a main
name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instal·lar dependències
        run: npm install

      - name: Build del projecte
        run: npm run build

      - name: Anàlisi amb ESLint
        run: npm run lint

      - name: Executar tests
        run: npm test

      - name: Deploy a Railway
        run: npx railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
